# ---
# NOTE:
# ---
# \ docker compose -f valkey_macos.yaml up --force-recreate
# \ valkey-cli -h 192.168.65.254 -p 7001 cluster nodes
# \ valkey-cli -h valkey-7002 -p 7002 cluster nodes
# \ docker network inspect bridge | grep Gateway > "Gateway": "172.17.0.1"

# ---
# Clean up:
# \ rm -rf valkey_client/setup/cluster-mode/prod/data
# \ docker compose -f valkey_macos.yaml down -v
# \ docker compose -f valkey_macos.yaml up --force-recreate
# ---

# ---
# ** NOTE: Do not use (double) quotation on command. It will hit a Valkey bug. If once, see "Clean up" above.
# ---

# version: ""
#  \ NOTE: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion.

services:
  # --- Master Nodes (7001‑7003) ---
  valkey-7001:
    image: valkey/valkey:latest
    container_name: valkey-7001
    ports:
      - "7001:7001"
      - "17001:17001"
    command: >
      valkey-server --port 7001
      --cluster-enabled yes
      --cluster-config-file /data/nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 192.168.65.254
      --cluster-announce-port 7001
      --cluster-announce-bus-port 17001
    volumes:
      - ./data/7001:/data

  valkey-7002:
    image: valkey/valkey:latest
    container_name: valkey-7002
    ports:
      - "7002:7002"
      - "17002:17002"
    command: >
      valkey-server --port 7002
      --cluster-enabled yes
      --cluster-config-file /data/nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 192.168.65.254
      --cluster-announce-port 7002
      --cluster-announce-bus-port 17002
    volumes:
      - ./data/7002:/data

  valkey-7003:
    image: valkey/valkey:latest
    container_name: valkey-7003
    ports:
      - "7003:7003"
      - "17003:17003"
    command: >
      valkey-server --port 7003
      --cluster-enabled yes
      --cluster-config-file /data/nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 192.168.65.254
      --cluster-announce-port 7003
      --cluster-announce-bus-port 17003
    volumes:
      - ./data/7003:/data

  # --- Replica Nodes (7004‑7006) ---
  valkey-7004:
    image: valkey/valkey:latest
    container_name: valkey-7004
    ports:
      - "7004:7004"
      - "17004:17004"
    command: >
      valkey-server --port 7004
      --cluster-enabled yes
      --cluster-config-file /data/nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 192.168.65.254
      --cluster-announce-port 7004
      --cluster-announce-bus-port 17004
    volumes:
      - ./data/7004:/data

  valkey-7005:
    image: valkey/valkey:latest
    container_name: valkey-7005
    ports:
      - "7005:7005"
      - "17005:17005"
    command: >
      valkey-server --port 7005
      --cluster-enabled yes
      --cluster-config-file /data/nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 192.168.65.254
      --cluster-announce-port 7005
      --cluster-announce-bus-port 17005
    volumes:
      - ./data/7005:/data

  valkey-7006:
    image: valkey/valkey:latest
    container_name: valkey-7006
    ports:
      - "7006:7006"
      - "17006:17006"
    command: >
      valkey-server --port 7006
      --cluster-enabled yes
      --cluster-config-file /data/nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 192.168.65.254
      --cluster-announce-port 7006
      --cluster-announce-bus-port 17006
    volumes:
      - ./data/7006:/data

  # --- Cluster Initializer ---
  cluster-init:
    image: valkey/valkey:latest
    container_name: valkey-cluster-init
    depends_on:
      - valkey-7001
      - valkey-7002
      - valkey-7003
      - valkey-7004
      - valkey-7005
      - valkey-7006
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Waiting for all 6 cluster nodes to be ready..."
        for port in 7001 7002 7003 7004 7005 7006; do
          until valkey-cli -h 192.168.65.254 -p $${port} ping > /dev/null 2>&1; do
            echo "Node at 192.168.65.254:$${port} not ready yet; retrying..."
            sleep 1
          done
          echo "Node at 192.168.65.254:$${port} is ready!"
        done

        echo "All nodes are up. Creating cluster…"
        sleep 2

        echo "yes" | valkey-cli --cluster create \
          192.168.65.254:7001 \
          192.168.65.254:7002 \
          192.168.65.254:7003 \
          192.168.65.254:7004 \
          192.168.65.254:7005 \
          192.168.65.254:7006 \
          --cluster-replicas 1

        echo "Cluster creation command sent. Waiting for cluster to be stable..."
        sleep 3

        until valkey-cli --cluster check 192.168.65.254:7001 2>&1 | grep -q '\[OK\] All 16384 slots covered.'; do
          echo "Cluster not stable yet; retrying in 2s..."
          sleep 2
        done

        echo "✅ Cluster is stable and all slots covered!"
