services:
  valkey-master:
    image: valkey/valkey:latest
    container_name: valkey-master
    ports:
      - "7201:7201"
    command: >
      valkey-server
      --port 7201
      --protected-mode no

  valkey-replica-1:
    image: valkey/valkey:latest
    container_name: valkey-replica-1
    ports:
      - "7202:7202"
    command: >
      valkey-server
      --port 7202
      --replicaof valkey-master 7201
      --protected-mode no
      --replica-announce-ip 127.0.0.1
      --replica-announce-port 7202
    depends_on:
      - valkey-master

  valkey-replica-2:
    image: valkey/valkey:latest
    container_name: valkey-replica-2
    ports:
      - "7203:7203"
    command: >
      valkey-server
      --port 7203
      --replicaof valkey-master 7201
      --protected-mode no
      --replica-announce-ip 127.0.0.1
      --replica-announce-port 7203
    depends_on:
      - valkey-master